# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Photo Studio Lab Manager' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  pod 'Firebase/Analytics'
  pod 'Firebase/Core'
  pod 'Firebase/Database'
  pod 'Firebase/Storage'
  pod 'Firebase/Auth'
  pod 'FAPanels'
  pod 'IQKeyboardManagerSwift'

  # Pods for Photo Studio Lab Manager

  target 'Photo Studio Lab ManagerTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'Photo Studio Lab ManagerUITests' do
    # Pods for testing
  end

end
